version: "3.9"
services:
  yolo:
    build: . 
    # image: nvidia/cuda:12.8.1-cudnn-devel-ubuntu20.04
    command: bash
    volumes:
      - /home/amigo/Documents/repos/hero_sam:/home/amigo/Documents/repos/hero_sam
    working_dir: /home/amigo/Documents/repos/hero_sam
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    stdin_open: true
    tty: true

