#ifndef YOLO_ONNX_ROS_CONFIG_HPP_
#define YOLO_ONNX_ROS_CONFIG_HPP_

#define YOLO_ONNX_FALSE 0
#define YOLO_ONNX_TRUE 1
#define YOLO_ONNX_ROS_CUDA_ENABLED YOLO_ONNX_FALSE

#endif //#define YOLO_ONNX_ROS_CONFIG_HPP_
